frontend_homepage:
    pattern:  /
    defaults: { _controller: FrontendBundle:Default:index }

frontend_empresa:
    pattern:  /empresa
    defaults: { _controller: FrontendBundle:Default:empresa }

frontend_contacto:
    pattern:  /contacto
    defaults: { _controller: FrontendBundle:Default:contacto }    